apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    app-name: pod-1
    purpose: pod-affinity
spec:         
  containers:
  - name: pod-1
    image: nginx   
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    app-name: pod-2
    purpose: pod-affinity
spec: 
  affinity:
    podAffinity:
      # requiredDuringSchedulingIgnoredDuringExecution: # hard rule pod-2 scheduled in pod-1
      # # ensure that Pods associated with this tenant land on the correct node pool
      #   - labelSelector:
      #       matchExpressions:
      #       - key: app-name
      #         operator: In
      #         values:
      #         - pod-1
      #     topologyKey: "kubernetes.io/hostname"
      preferredDuringSchedulingIgnoredDuringExecution: # soft rule pod-2 schedule in pod-1 in preffer some not sure scheduled
      - weight: 1
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app-name
              operator: In
              values:
              - pod-1
          topologyKey: "kubernetes.io/hostname"    
  containers:
  - name: pod-2
    image: nginx 